### ISSUE TITLE
Add ability to deactivate facility without deleting or sending to EPA

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/iaip#1177]
Reported by Sean [via Zendesk](https://gaepd.zendesk.com/agent/tickets/8227):

> IAIP is not letting me Remove or Destroy facilities in the Facility Creator tool, saying that "Facility has Permit fees data. Unable to delete unless the fees data is removed first." These facilities I'm trying to remove/destroy haven't even been approved, so there is no permit fees data except for permit application fees, which have been paid and are not being returned, so I'm not sure what to do.

-- 

### Tasks

- [x] Update IAIP DB scripts
- [x] Update IAIP facility creator
- [x] Update IAIP Facility Summary
- [x] Update ICIS-Air scripts
