### ISSUE TITLE
Put the Emissions Statement module in read-only mode

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/iaip#1272]
The Emissions Statement is no longer required. See https://github.com/gaepdit/geco/issues/586 for background. This tool can be put in read-only mode.
```[tasklist]
### Tasks
- [x] Fix ES query bugs
- [x] Remove ES write tools (but keep the view tools)
- [x] Remove ES access permissions from GECO user tools
- [x] Remove ES from facility contact editor
- [x] Remove ES facility contacts (facility summary, etc.)
- [x] Clean up GECO user tools
```
