### ISSUE TITLE
Create connections API and set up new build and deploy workflow

### ISSUE THREAD

**Issue by dougwaldron** [gaepdit/iaip#1295]
Let's use GitHub pages to host the IAIP webpage and installer files. 

A GitHub action will build the ClickOnce installer files and publish them to GitHub Pages. (The webpage can continue to be built locally using Pandoc, but eventually that can be automated as well.)

GitHub Pages is only available for public repositories (unless on a paid plan, but that would take too long to set up), so the IAIP repo needs to be recreated as public. This means removing the DB passwords. But to do that, the IAIP will need to get a new login mechanism since the current mechanism requires direct DB access. 

To accomplish this, a new web API will be created and deployed behind the VPN (on a dev or test server). IAIP will send login details to the API and, if valid, the API will return the DB PW for use during the current session.

```[tasklist]
### Tasks
- [x] Create a new public IAIP repo for testing
- [x] Set up a GitHub action to build the application
- [x] Add the old website to the new repo using GitHub Pages
- [x] Point temp URL to GitHub Pages site
- [x] Create a web API project to log in user and provide app secrets
- [x] Modify the IAIP to use the web API for login
- [x] Make sure existing JSON serialization in IAIP is still working
- [x] Add additional API endpoints required by the IAIP Login form
- [x] Remove all app secrets from the updated IAIP code
- [x] Deploy the web API to the UAT server
- [x] Deploy Dev & UAT versions of IAIP using the new API
- [x] Add Raygun to CX API app
- [x] Modify the GitHub action to publish the application to GitHub Pages
- [x] Update the deployment and certificate instructions
- [x] Automate web page deployment
- [x] Test thoroughly
- [x] Manually publish updated IAIP to existing on-prem website
- [x] Reset any public API keys (Raygun, Google Maps)
- [x] Disable the `iaip_app_user` database accounts
- [x] Deploy API to prod server
- [x] Make this repo public
- [x] Start setting up GitHub Pages for this repo using the prod "iaip" URL
- [ ] https://github.com/gaepdit/iaip/issues/1308
- [x] Finish configuring GitHub Pages
- [x] Delete the temp "iaip-app" repo when no longer needed -- AFTER removing the dev URL from DNS
- [x] Stop "iaip" website in prod IIS
- [x] Delete "iaip-cx" from test server
- [x] Delete "iaip" website and files from prod server
```

Refs:
* [Build and publish ClickOnce installer on GitHub | Jan Jones](https://janjones.me/posts/clickonce-installer-build-publish-github/)
* [Building ClickOnce Applications from the Command Line - Visual Studio (Windows) | Microsoft Learn](https://learn.microsoft.com/en-us/visualstudio/deployment/building-clickonce-applications-from-the-command-line?view=vs-2022)
* [Publish ClickOnce application using Publish wizard - Visual Studio (Windows) | Microsoft Learn](https://learn.microsoft.com/en-us/visualstudio/deployment/how-to-publish-a-clickonce-application-using-the-publish-wizard?view=vs-2022)
* [Managing a custom domain for your GitHub Pages site - GitHub Docs](https://docs.github.com/en/pages/configuring-a-custom-domain-for-your-github-pages-site/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain)
* [How to Host ClickOnce Installer on GitHub](https://www.jeeshenlee.com/2020/10/how-to-host-clickonce-installer-on.html)
* [microsoft/github-actions-for-desktop-apps: This repo contains a sample WPF application to demonstrate how to create CI/CD pipelines using GitHub Actions.](https://github.com/microsoft/github-actions-for-desktop-apps#signing)
* [MSBuild Command-Line Reference - MSBuild | Microsoft Learn](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2022)
* [VB.NET || How To Send, Post & Process A REST API Web Request Using VB.NET – My Programming Notes](https://www.programmingnotes.org/6229/vb-net-how-to-send-post-process-a-rest-api-web-request-using-vb-net/)
* [actions/checkout: Action for checking out a repo](https://github.com/actions/checkout?tab=readme-ov-file#Checkout-a-different-branch)

```[tasklist]
### API endpoints needed
- [x] login
- [x] session
- [x] status
- [x] RequestUsernameReminder
- [x] ResetUserPassword
- [x] RequestResetUserPassword
```
